### ISSUE TITLE
WhenTaproot project

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Meta#347]
![image](https://user-images.githubusercontent.com/55287964/178905800-dfc90472-12df-4c59-ab37-dcbeed22aff0.png)

Making an issue to track details relating to the WhenTaproot project Steve, Murch and Stephen initiated. We have a Slack channel called #bech32m-adoption where discussions around this project are happening. Below are some details of the project

### Campaign goal

Increase bech32m (Taproot, P2TR) adoption in the bitcoin ecosystem. Taproot has been out since November 2021 but [adoption is still quite low](https://en.bitcoin.it/wiki/Bech32_adoption) and usage is even lower ([Only 11k BTC (0.05%) of all bitcoin), and 0.0012% of all UTXOs at time of posting](https://txstats.com/dashboard/db/taproot-statistics?orgId=1)). 

### Milestones

- [ ] Create a simple static website (whentaproot.org / .com acquired by @moneyball)
    - [ ] States problem, sells solution   
    - [ ] Start by tracking adoption in a chart similar to [bitcoinqr.dev](https://bitcoinqr.dev/)
- [ ] Start reaching out to bitcoin service providers on the chart and politely ask them what their Taproot adoption plans are
- [ ] Test Bitcoin providers taproot implementation to ensure it works (include this in the chart) 
 
### Other ideas

- Offer a template message on website that end users can copy and share with service providers they use to get them to adopt bech32m
- Track usage on website, could import [one of these charts](https://txstats.com/dashboard/db/taproot-statistics?orgId=1)
- Write a Taproot blog series [similar to bech32 series](https://bitcoinops.org/en/bech32-sending-support/) by David Harding
- List projects that are using Taproot to build cool new products on the website
- List possible projects that could be made available with Taproot adoption on the website (e.g. FROST)
- We could include a QR code for a Taproot address on the website that people could scan to see their wallet supports sending to them
- Use the [WhenTaproot](https://twitter.com/WhenTaproot) twitter account to share updates on campaign / other Taproot related information 
- Link to resources for devs who are looking to implement Taproot in their product or service

### Resources

- Taproot statistics: https://txstats.com/dashboard/db/taproot-statistics?orgId=1
- Taproot adoption Wiki: https://en.bitcoin.it/wiki/Bech32_adoption
- BitcoinQR campaign: https://bitcoinqr.dev/ 
- WhenSegWit campaign for bech32 adoption: https://whensegwit.com/
- Designing for Taproot by @sbddesign: https://d.elor.me/2022/06/designing-for-taproot/
- Bech32 blog series by David Harding: https://bitcoinops.org/en/bech32-sending-support/ 
- Bech32m BIP 350: https://github.com/bitcoin/bips/blob/master/bip-0350.mediawiki

**Comment by Bosch-0** [comment]
Made some issues about adding Taproot benefits to the transaction details for the below block explorers

- https://github.com/Blockstream/esplora/issues/396
- https://github.com/mempool/mempool/issues/2107

**Comment by moneyball** [comment]
Another resource: https://bitcoinops.org/en/preparing-for-taproot/#bech32m-sending-support

**Comment by GBKS** [comment]
[The website](https://whentaproot.org) has been live for some time, has its own repo & socials and there is no activity in this issue, so I'm going to close this issue.
